export { getToolRenderer, hasToolRenderer, registerToolRenderer } from './registry'
export { StructuredFallback } from './StructuredFallback'

// Auto-register all renderers
import './renderers/BashRenderer'
import './renderers/BrowserSubmitRenderer'
import './renderers/EditRenderer'
import './renderers/GrepRenderer'
import './renderers/ReadRenderer'
import './renderers/SkillRenderer'
import './renderers/WriteRenderer'
import './renderers/AskUserQuestionRenderer'
import './renderers/BriefRenderer'
import './renderers/ConfigRenderer'
import './renderers/CronCreateRenderer'
import './renderers/CronDeleteRenderer'
import './renderers/CronListRenderer'
import './renderers/EnterPlanModeRenderer'
import './renderers/EnterWorktreeRenderer'
import './renderers/ExitPlanModeRenderer'
import './renderers/ExitWorktreeRenderer'
import './renderers/GlobRenderer'
import './renderers/ListMcpResourcesRenderer'
import './renderers/LSPToolRenderer'
import './renderers/NotebookEditRenderer'
import './renderers/PowerShellRenderer'
import './renderers/ReadMcpResourceRenderer'
import './renderers/RemoteTriggerRenderer'
import './renderers/SendMessageRenderer'
import './renderers/TaskGetRenderer'
import './renderers/TaskListRenderer'
import './renderers/TaskOutputRenderer'
import './renderers/TaskStopRenderer'
import './renderers/TeamCreateRenderer'
import './renderers/TeamDeleteRenderer'
import './renderers/TodoWriteRenderer'
import './renderers/ToolSearchRenderer'
import './renderers/WebFetchRenderer'
import './renderers/WebSearchRenderer'
