import '../src/server/test-utils/test-env.js';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rename, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from 'playwright';
import gitGraphRouter from '../src/server/routes/git-graph.js';
import { store } from '../src/server/storage/sqlite-store.js';
import { gitRepositoryService } from '../src/server/services/git-repository-service.js';

const fixtureRoot = await mkdtemp(path.join(os.tmpdir(), 'comate-graph-browser-'));
const screenshots = await mkdtemp(path.join(os.tmpdir(), 'comate-graph-screenshots-'));
const git = (cwd: string, args: string[]) => execFileSync('git', args, { cwd, stdio: 'ignore' });
async function repository(relative: string) {
  const cwd = path.join(fixtureRoot, relative);
  await mkdir(cwd, { recursive: true });
  git(cwd, ['init', '-b', 'main']);
  git(cwd, ['config', 'user.name', 'Graph QA']);
  git(cwd, ['config', 'user.email', 'graph@example.com']);
  await mkdir(path.join(cwd, 'src'));
  await writeFile(path.join(cwd, 'src/index.ts'), `export const project = '${relative}';\n`);
  git(cwd, ['add', '.']);
  git(cwd, ['commit', '-m', `Initialize ${relative}`]);
  git(cwd, ['checkout', '-b', 'feature']);
  await writeFile(path.join(cwd, 'src/index.ts'), `export const project = '${relative} updated';\n`);
  git(cwd, ['commit', '-am', `Update ${relative}`]);
  return cwd;
}
const a = await repository('apps/a');
await repository('services/b');
await repository('nested/deeper/c');
git(a, ['-c', 'protocol.file.allow=always', 'submodule', 'add', path.join(fixtureRoot, 'services/b'), 'module']);
git(a, ['commit', '-am', 'Add initialized module']);
const workspace = await store.create({ name: 'Multi-repo QA', folderPath: fixtureRoot });
const vite = await createServer({ configFile: false, plugins: [react()],
  resolve: { alias: { '@server': path.resolve('src/server'), '@': path.resolve('src/client') } },
  server: { middlewareMode: true, hmr: false }, appType: 'custom' });
const app = express();
app.use('/api/workspaces/:id/git-graph', gitGraphRouter);
app.use('/api', (_req, res) => { res.json({}); });
app.use(vite.middlewares);
app.get('/qa', async (req, res) => {
  res.type('html').send(await vite.transformIndexHtml(req.originalUrl, '<html><head></head><body><div id="root"></div><script type="module" src="/scripts/fixtures/multi-repo-graph.tsx"></script></body></html>'));
});
const server = app.listen(0, '127.0.0.1');
await new Promise<void>((resolve) => server.once('listening', resolve));
const address = server.address() as { port: number };
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1100, height: 800 } });
  page.setDefaultTimeout(20_000);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('pageerror', (error) => console.error(error.message));
  const url = `http://127.0.0.1:${address.port}/qa?workspace=${workspace.id}&folder=${encodeURIComponent(fixtureRoot)}`;
  await page.goto(url);
  const selector = page.getByRole('combobox', { name: 'Repository' });
  await selector.locator('option').filter({ hasText: 'apps/a/module' }).waitFor({ state: 'attached' });
  const options = await selector.locator('option').evaluateAll((elements) => elements.map((el) => ({ value: (el as HTMLOptionElement).value, text: el.textContent! })));
  assert.equal(options.length, 4);
  const aId = options.find((item) => item.text === 'a — apps/a')!.value;
  const bId = options.find((item) => item.text === 'b — services/b')!.value;
  assert.equal(await selector.inputValue(), aId);
  await page.getByRole('option', { name: /Update apps\/a/ }).click();
  await page.getByRole('button', { name: /src\/index.ts/ }).click();
  await page.getByText("apps/a updated", { exact: false }).last().waitFor();
  await page.screenshot({ path: path.join(screenshots, 'diff-wide.png') });
  await page.getByRole('button', { name: 'Back to graph' }).click();
  await page.getByRole('searchbox').fill('Update');
  await selector.selectOption(bId);
  await page.getByRole('option', { name: /Update services\/b/ }).waitFor();
  assert.equal(await page.getByRole('searchbox').inputValue(), '');
  await selector.selectOption(aId);
  await page.getByRole('option', { name: /Update apps\/a/ }).waitFor();
  assert.equal(await page.getByRole('searchbox').inputValue(), 'Update');
  await page.screenshot({ path: path.join(screenshots, 'graph-wide.png') });
  await page.setViewportSize({ width: 420, height: 760 });
  await page.reload();
  await page.getByRole('option', { name: /Update apps\/a/ }).waitFor();
  await selector.focus();
  await page.keyboard.press('Space');
  await page.keyboard.press('b');
  await page.keyboard.press('Enter');
  assert.equal(await selector.inputValue(), bId);
  await page.getByRole('option', { name: /Update services\/b/ }).waitFor();
  await page.screenshot({ path: path.join(screenshots, 'graph-narrow.png') });
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.screenshot({ path: path.join(screenshots, 'graph-dark.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await repository('new-project');
  await page.getByRole('button', { name: 'Rescan repositories' }).click();
  await selector.locator('option').filter({ hasText: 'new-project' }).waitFor({ state: 'attached' });
  await rename(path.join(fixtureRoot, 'services/b'), path.join(screenshots, 'removed-repository'));
  await page.getByRole('button', { name: 'Rescan repositories' }).click();
  await selector.locator(`option[value="${bId}"]`).waitFor({ state: 'detached' });
  assert.notEqual(await selector.inputValue(), bId);
  assert.deepEqual(errors, []);
  console.log(`Browser acceptance passed. Screenshots: ${screenshots}`);
} finally {
  await browser.close();
  await vite.close();
  await new Promise<void>((resolve) => server.close(() => resolve()));
  await gitRepositoryService.dispose();
  await store.delete(workspace.id);
  await rm(fixtureRoot, { recursive: true, force: true });
  await rm(path.join(screenshots, 'removed-repository'), { recursive: true, force: true });
}
